alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

if [ `uname` = "Darwin" ]; then
  alias ll="ls -lGF"
  alias la="ls -alGF"
  alias ls="ls -G"
else
  alias ll="ls -lF --color=auto"
  alias la="ls -alF --color=auto"
  alias ls="ls --color=auto"
fi

alias grep="grep --color=auto"

alias em='emacsclient -nc -a "" -F "((fullscreen . maximized))"'
alias emc='emacsclient -t -a ""'

# EDITOR='emacsclient -a ""'
# alias tmux="tmux -2"
