# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
# ZSH_THEME="af-magic"
# ZSH_THEME="dpoggi"
ZSH_THEME="seeker"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git vagrant scala sbt python pip tmux colored-man common-aliases cp sudo zsh-syntax-highlighting z bundler)

source $ZSH/oh-my-zsh.sh

# Customize
unsetopt correct_all

# Aliases
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

# Profile
if [ -f ~/.bash_profile ]; then
    source ~/.bash_profile
fi
